#!/usr/bin/env zsh

ZSH_CONFIG_DIR="${HOME}/.zsh.d"

# 各設定ファイルを読み込み
source "${ZSH_CONFIG_DIR}/path.zsh"
source "${ZSH_CONFIG_DIR}/dev-tools.zsh"
source "${ZSH_CONFIG_DIR}/aliases.zsh"
source "${ZSH_CONFIG_DIR}/fzf.zsh"

# Starship
eval "$(starship init zsh)"

# Sheldon
eval "$(sheldon source)"
