# Sheldon Plugin Configuration
# https://sheldon.cli.rs/

shell = "zsh" 

# ref: <https://sheldon.cli.rs/Examples.html?highlight=defer#deferred-loading-of-plugins-in-zsh>
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


# =============================
# Plugins
# =============================

# <https://github.com/olets/zsh-abbr>
[plugins.zsh-abbr]
github = "olets/zsh-abbr"

# <https://github.com/olets/zsh-window-title>
[plugins.zsh-window-title]
github = "olets/zsh-window-title"
apply = ["defer"]

# <https://github.com/zsh-users/zsh-autosuggestions>
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

# <https://github.com/zdharma-continuum/fast-syntax-highlighting>
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

# <https://github.com/5A6F65/fast-abbr-highlighting>
[plugins.fast-abbr-highlighting]
github = "5A6F65/fast-abbr-highlighting"

# <https://github.com/zsh-users/zsh-completions>
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

# <https://github.com/zpm-zsh/ls>
[plugins.zpm-zsh-ls]
github = "zpm-zsh/ls"
apply = ["defer"]

# <https://github.com/alexiszamanidis/zsh-git-fzf>
[plugins.zsh-git-fzf]
github = "alexiszamanidis/zsh-git-fzf"
apply = ["defer"]

# <https://github.com/ajeetdsouza/zoxide>
[plugins.zoxide]
github = "ajeetdsouza/zoxide"
use = ["zoxide.plugin.zsh"]
apply = ["defer"]

[plugins.compinit]
inline = '''
autoload -Uz compinit
# once a day
for dump in ~/.zcompdump(N.mh+24); do
    compinit; return
done
compinit -C
'''

# ==============================
# Plugin Hooks
# ==============================

[plugins.zpm-zsh-ls.hooks]
pre = '''
export ZSH_LS_BACKEND="eza"
export ZSH_LS_DISABLE_GIT=false
'''
