[settings]
idiomatic_version_file = true
auto_install = true
install_before = "1d"

[settings.npm]
package_manager = "pnpm"

[tools]
node = "lts"
bun = "latest"
python = "latest"
pnpm = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
eza = "latest"
gh = "latest"
helix = "latest"
lazygit = "latest"
fzf = "latest"
ripgrep = "latest"
shfmt = "latest"
zellij = "latest"
zoxide = "latest"
"npm:difit" = "latest"
"npm:ccusage" = "latest"
"npm:portless" = "latest"
"npm:skills" = "latest"
"npm:agent-browser" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@nyatinte/prw" = "latest"
